---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, astra trident, trident for docker, docker, logs, binary, managed plugin 
summary: È possibile raccogliere i registri per ottenere assistenza nella risoluzione dei problemi. Il metodo utilizzato per raccogliere i log varia in base alla modalità di esecuzione del plug-in Docker. 
---
= Raccogliere i log
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile raccogliere i registri per ottenere assistenza nella risoluzione dei problemi. Il metodo utilizzato per raccogliere i log varia in base alla modalità di esecuzione del plug-in Docker.



== Raccogliere i registri per la risoluzione dei problemi

.Fasi
. Se si esegue Astra Trident utilizzando il metodo di plugin gestito consigliato (ad esempio, utilizzando `docker plugin` e visualizzarli come segue:
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
Il livello di registrazione standard dovrebbe consentire di diagnosticare la maggior parte dei problemi. Se non è sufficiente, è possibile attivare la registrazione di debug.

. Per abilitare la registrazione del debug, installare il plug-in con la registrazione del debug attivata:
+
[listing]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
In alternativa, attivare la registrazione del debug quando il plug-in è già installato:

+
[listing]
----
docker plugin disable <plugin>
docker plugin set <plugin> debug=true
docker plugin enable <plugin>
----
. Se si esegue il file binario stesso sull'host, i registri sono disponibili nell'host `/var/log/netappdvp` directory. Per attivare la registrazione di debug, specificare `-debug` quando si esegue il plug-in.




== Suggerimenti generali per la risoluzione dei problemi

* Il problema più comune in cui i nuovi utenti eseguono è una configurazione errata che impedisce l'inizializzazione del plug-in. In questo caso, quando si tenta di installare o abilitare il plug-in, viene visualizzato un messaggio simile al seguente:
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
Ciò significa che il plug-in non è stato avviato. Fortunatamente, il plug-in è stato creato con una funzionalità di registrazione completa che dovrebbe aiutarti a diagnosticare la maggior parte dei problemi che probabilmente si verificano.

* In caso di problemi con il montaggio di un PV su un container, assicurarsi che `rpcbind` è installato e in esecuzione. Utilizzare il gestore dei pacchetti richiesto per il sistema operativo host e verificare se `rpcbind` è in esecuzione. È possibile controllare lo stato del servizio rpcbind eseguendo un `systemctl status rpcbind` o equivalente.

