---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, astra trident, trident for docker, docker, upgrade trident for docker 
summary: 'Puoi aggiornare Astra Trident per Docker senza alcun impatto sui volumi in uso. Durante il processo di aggiornamento, ci sarà un breve periodo in cui `docker volume` i comandi diretti al plugin non avranno successo e le applicazioni non potranno montare i volumi fino a quando il plugin non verrà eseguito di nuovo. Nella maggior parte dei casi, si tratta di pochi secondi.' 
---
= Aggiornare o disinstallare Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi aggiornare Astra Trident per Docker senza alcun impatto sui volumi in uso. Durante il processo di aggiornamento, ci sarà un breve periodo in cui `docker volume` i comandi diretti al plugin non avranno successo e le applicazioni non potranno montare i volumi fino a quando il plugin non verrà eseguito di nuovo. Nella maggior parte dei casi, si tratta di pochi secondi.



== Eseguire l'upgrade

Per aggiornare Astra Trident per Docker, attenersi alla procedura riportata di seguito.

.Fasi
. Elencare i volumi esistenti:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Disattivare il plug-in:
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Aggiornare il plug-in:
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: La release 18.01 di Astra Trident sostituisce l'nDVP. È necessario eseguire l'aggiornamento direttamente da `netapp/ndvp-plugin` al `netapp/trident-plugin` immagine.

. Attivare il plug-in:
+
[listing]
----
docker plugin enable netapp:latest
----
. Verificare che il plug-in sia attivato:
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Verificare che i volumi siano visibili:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
+

IMPORTANT: Se si esegue l'aggiornamento da una versione precedente di Astra Trident (precedente alla 20.10) ad Astra Trident 20.10 o successiva, potrebbe verificarsi un errore. Per ulteriori informazioni, vedere link:known-issues-docker.html["Problemi noti"^]. Se si verifica l'errore, disattivare il plug-in, quindi rimuovere il plug-in e installare la versione richiesta di Astra Trident passando un parametro di configurazione aggiuntivo: `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`





== Disinstallare

Per disinstallare Astra Trident per Docker, procedere come segue.

.Fasi
. Rimuovere tutti i volumi creati dal plug-in.
. Disattivare il plug-in:
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Rimuovere il plug-in:
+
[listing]
----
docker plugin rm netapp:latest
----

