---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Scopri come configurare un backend ONTAP con i driver NAS ONTAP. 
---
= Panoramica del driver NAS ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informazioni sulla configurazione di un backend ONTAP con driver NAS ONTAP e Cloud Volumes ONTAP.



== Dettagli del driver NAS ONTAP

Astra Trident offre i seguenti driver di storage NAS per comunicare con il cluster ONTAP. Le modalità di accesso supportate sono: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Se stai utilizzando Astra Control per protezione, recovery e mobilità, leggi <<Compatibilità driver Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Driver | Protocollo | VolumeMode | Modalità di accesso supportate | File system supportati 


| `ontap-nas`  a| 
NFS
PMI
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-economy`  a| 
NFS
PMI
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-flexgroup`  a| 
NFS
PMI
 a| 
Filesystem
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`

|===


=== Compatibilità driver Astra Control

Astra Control offre protezione perfetta, disaster recovery e mobilità (spostamento di volumi tra cluster Kubernetes) per i volumi creati con `ontap-nas`, `ontap-nas-flexgroup`, e. `ontap-san` driver. Vedere link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Prerequisiti per la replica di Astra Control"^] per ulteriori informazioni.

[WARNING]
====
* Utilizzare `ontap-san-economy` solo se si prevede che il conteggio dell'utilizzo persistente del volume sia superiore a. link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^].
* Utilizzare `ontap-nas-economy` solo se si prevede che il conteggio dell'utilizzo persistente del volume sia superiore a. link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limiti di volume ONTAP supportati"^] e a. `ontap-san-economy` impossibile utilizzare il driver.
* Non utilizzare `ontap-nas-economy` se prevedete la necessità di protezione dei dati, disaster recovery o mobilità.


====


== Autorizzazioni utente

Astra Trident prevede di essere eseguito come amministratore di ONTAP o SVM, in genere utilizzando `admin` utente del cluster o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo.

Per le implementazioni di Amazon FSX per NetApp ONTAP, Astra Trident prevede di essere eseguito come amministratore di ONTAP o SVM, utilizzando il cluster `fsxadmin` utente o a. `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo. Il `fsxadmin` user è un sostituto limitato per l'utente amministratore del cluster.


NOTE: Se si utilizza `limitAggregateUsage` parametro, sono richieste le autorizzazioni di amministrazione del cluster. Quando si utilizza Amazon FSX per NetApp ONTAP con Astra Trident, il `limitAggregateUsage` il parametro non funziona con `vsadmin` e. `fsxadmin` account utente. L'operazione di configurazione non riesce se si specifica questo parametro.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP che un driver Trident può utilizzare, non lo consigliamo. La maggior parte delle nuove release di Trident chiamerà API aggiuntive che dovrebbero essere considerate, rendendo gli aggiornamenti difficili e soggetti a errori.
