---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Utilizzando Astra Trident con Amazon FSX per NetApp ONTAP, puoi garantire che i cluster Kubernetes in esecuzione in Amazon Elastic Kubernetes Service (EKS) possano eseguire il provisioning di volumi persistenti di blocchi e file supportati da ONTAP.' 
---
= Utilizza Astra Trident con Amazon FSX per NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX per NetApp ONTAP"^] È un servizio AWS completamente gestito che consente ai clienti di lanciare ed eseguire file system basati sul sistema operativo per lo storage NetApp ONTAP. FSX per ONTAP consente di sfruttare le funzionalità, le performance e le funzionalità amministrative di NetApp che conosci, sfruttando al contempo la semplicità, l'agilità, la sicurezza e la scalabilità dell'archiviazione dei dati su AWS. FSX per ONTAP supporta le funzionalità del file system ONTAP e le API di amministrazione.



== Panoramica

Un file system è la risorsa principale di Amazon FSX, simile a un cluster ONTAP on-premise. All'interno di ogni SVM è possibile creare uno o più volumi, ovvero contenitori di dati che memorizzano i file e le cartelle nel file system. Con Amazon FSX per NetApp ONTAP, Data ONTAP verrà fornito come file system gestito nel cloud. Il nuovo tipo di file system è denominato *NetApp ONTAP*.

Utilizzando Astra Trident con Amazon FSX per NetApp ONTAP, puoi garantire che i cluster Kubernetes in esecuzione in Amazon Elastic Kubernetes Service (EKS) possano eseguire il provisioning di volumi persistenti di file e blocchi supportati da ONTAP.



== Considerazioni

* Volumi SMB:
+
** I volumi SMB sono supportati utilizzando `ontap-nas` solo driver.
** I volumi SMB non sono supportati con il componente aggiuntivo Astra Trident EKS.
** Astra Trident supporta volumi SMB montati su pod eseguiti solo su nodi Windows.


* Prima di Astra Trident 24,02, i volumi creati su file system Amazon FSX con backup automatici abilitati, non possono essere eliminati da Trident. Per evitare questo problema in Astra Trident 24,02 o versioni successive, specifica il `fsxFilesystemID`, AWS `apiRegion`, AWS `apikey`E AWS `secretKey` Nel file di configurazione back-end per AWS FSX per ONTAP.
+

NOTE: Se stai specificando un ruolo IAM in Astra Trident, puoi omettere di specificare `apiRegion`, `apiKey`, e. `secretKey` Campi di Astra Trident esplicitamente. Per ulteriori informazioni, fare riferimento a. link:../trident-use/trident-fsx-examples.html["FSX per le opzioni di configurazione e gli esempi di ONTAP"].





== Dettagli del driver FSX per ONTAP

Puoi integrare Astra Trident con Amazon FSX per NetApp ONTAP utilizzando i seguenti driver:

* `ontap-san`: Ogni PV fornito è un LUN all'interno del proprio volume Amazon FSX per NetApp ONTAP.
* `ontap-san-economy`: Ogni PV fornito è un LUN con un numero configurabile di LUN per volume Amazon FSX per NetApp ONTAP.
* `ontap-nas`: Ogni PV fornito è un volume Amazon FSX completo per NetApp ONTAP.
* `ontap-nas-economy`: Ogni PV fornito è un qtree, con un numero configurabile di qtree per ogni volume Amazon FSX per NetApp ONTAP.
* `ontap-nas-flexgroup`: Ogni PV fornito è un volume Amazon FSX completo per NetApp ONTAP FlexGroup.


Per informazioni dettagliate sul conducente, fare riferimento a. link:../trident-use/ontap-nas.html["Driver NAS"] e. link:../trident-use/ontap-san.html["Driver SAN"].



== Autenticazione

Astra Trident offre due modalità di autenticazione.

* Basato su certificato: Astra Trident comunicherà con SVM sul file system FSX utilizzando un certificato installato sulla SVM.
* Basato sulle credenziali: È possibile utilizzare `fsxadmin` utente per il file system o l' `vsadmin` Configurato dall'utente per la SVM.
+

WARNING: Astra Trident prevede di essere eseguito come a. `vsadmin` Utente SVM o come utente con un nome diverso che ha lo stesso ruolo. Amazon FSX per NetApp ONTAP ha un `fsxadmin` Utente che sostituisce in maniera limitata il ONTAP `admin` utente del cluster. Si consiglia vivamente di utilizzare `vsadmin` Con Astra Trident.



È possibile aggiornare i back-end per passare da un metodo basato su credenziali a un metodo basato su certificato. Tuttavia, se si tenta di fornire *credenziali e certificati*, la creazione del backend non riesce. Per passare a un metodo di autenticazione diverso, è necessario rimuovere il metodo esistente dalla configurazione di back-end.

Per ulteriori informazioni sull'attivazione dell'autenticazione, fare riferimento all'autenticazione per il tipo di driver in uso:

* link:ontap-nas-prep.html["Autenticazione NAS ONTAP"]
* link:ontap-san-prep.html["Autenticazione SAN ONTAP"]




== Identità cloud per EKS

L'identità del cloud consente ai pod Kubernetes di accedere alle risorse AWS eseguendo l'autenticazione come ruolo AWS IAM anziché fornire credenziali AWS esplicite.

Per sfruttare l'identità cloud in AWS, è necessario disporre di:

* Un cluster Kubernetes implementato utilizzando EKS
* Astra Trident ha installato che include `cloudProvider` specifica `"AWS"` e. `cloudIdentity` Specifica del ruolo AWS IAM.
+
[role="tabbed-block"]
====
.Operatore Trident
--
Per installare Astra Trident usando l'operatore Trident, modifica `tridentorchestrator_cr.yaml` da impostare `cloudProvider` a. `"AWS"` e impostare `cloudIdentity` Al ruolo AWS IAM.

Ad esempio:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "AWS"
  cloudIdentity: "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"
----
--
.Timone
--
Impostare i valori per i flag *cloud provider* e *cloud Identity* utilizzando le seguenti variabili di ambiente:

`export CP="AWS"`
`export CI="'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"`

Nell'esempio seguente viene installato e impostato Astra Trident `cloudProvider` a. `AWS` utilizzo della variabile di ambiente `$CP` E imposta "cloudIdentity" utilizzando la variabile d'ambiente `$CI`:

[listing]
----
helm install trident trident-operator-100.2402.0.tgz --set cloudProvider=$CP --set cloudIdentity=$CI
----
--
.<code>tridentctl</code>
--
Impostare i valori per i flag *cloud provider* e *cloud Identity* utilizzando le seguenti variabili di ambiente:

`export CP="AWS"`
`export CI="'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"`

Nell'esempio seguente viene installato Astra Trident e impostato l' `cloud-provider` contrassegna come `$CP`, e. `cloud-identity` a. `$CI`:

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====




== Trova ulteriori informazioni

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentazione di Amazon FSX per NetApp ONTAP"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Post del blog su Amazon FSX per NetApp ONTAP"^]

