---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm, attributes, customize 
summary: È possibile utilizzare il programma di installazione di Astra Trident per personalizzare la distribuzione. 
---
= Personalizzare l'installazione di tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il programma di installazione di Astra Trident per personalizzare l'installazione.



== Informazioni sul programma di installazione

Il programma di installazione di Astra Trident consente di personalizzare gli attributi. Ad esempio, se l'immagine Trident è stata copiata in un repository privato, è possibile specificare il nome dell'immagine utilizzando `--trident-image`. Se l'immagine Trident e le immagini sidecar CSI necessarie sono state copiate in un repository privato, potrebbe essere preferibile specificare la posizione di tale repository utilizzando `--image-registry` switch, che assume la forma `<registry FQDN>[:port]`.

Se stai usando una distribuzione di Kubernetes, dove `kubelet` mantiene i dati su un percorso diverso dal solito `/var/lib/kubelet`, è possibile specificare il percorso alternativo utilizzando `--kubelet-dir`.

Se è necessario personalizzare l'installazione oltre a quanto consentito dall'argomento del programma di installazione, è possibile personalizzare i file di distribuzione. Utilizzando il `--generate-custom-yaml` Il parametro crea i seguenti file YAML nel programma di installazione `setup` directory:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


Dopo aver generato questi file, è possibile modificarli in base alle proprie esigenze e utilizzarli `--use-custom-yaml` per installare l'implementazione personalizzata.

[listing]
----
./tridentctl install -n trident --use-custom-yaml
----