---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: 'Scopri di più su tridentctl, un"utility della riga di comando che offre un accesso semplice a Trident.' 
---
= Gestisci Astra Trident usando tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il https://github.com/NetApp/trident/releases["Pacchetto di installazione Trident"^] include il `tridentctl` Command-line utility per fornire un semplice accesso ad Astra Trident. Gli utenti Kubernetes con privilegi sufficienti possono usarlo per installare Astra Trident o gestire il namespace che contiene il pod Astra Trident.



== Comandi e flag globali

Puoi correre `tridentctl help` per ottenere un elenco di comandi disponibili per `tridentctl` o aggiungere il `--help` flag a qualsiasi comando per ottenere un elenco di opzioni e flag per quel comando specifico.

Utilizzo::


[listing]
----
tridentctl [command] [--optional-flag]
----
Astra Trident `tridentctl` utility supporta i seguenti comandi e flag globali.

.Comandi
[%collapsible]
====
`create`:: Aggiungi una risorsa a Astra Trident.
`delete`:: Rimozione di una o più risorse da Astra Trident.
`get`:: Ottieni una o più risorse da Astra Trident.
`help`:: Aiuto su qualsiasi comando.
`images`:: Stampare una tabella delle immagini container di cui Astra Trident ha bisogno.
`import`:: Importa una risorsa esistente in Astra Trident.
`install`:: Installa Astra Trident.
`logs`:: Stampare i registri da Astra Trident.
`send`:: Invia una risorsa da Astra Trident.
`uninstall`:: Disinstallare Astra Trident.
`update`:: Modifica una risorsa in Astra Trident.
`update backend state`:: Sospendere temporaneamente le operazioni di backend.
`upgrade`:: Aggiorna una risorsa in Astra Trident.
`version`:: Stampa la versione di Astra Trident.


====
.Flag globali
[%collapsible]
====
`-d`, `--debug`:: Output di debug.
`-h`, `--help`:: Aiuto per `tridentctl`.
`-n`, `--namespace string`:: Namespace dell'implementazione di Astra Trident.
`-o`, `--output string`:: Formato di output. Uno tra json|yaml|name|wide|ps (impostazione predefinita).
`-s`, `--server string`:: Indirizzo/porta dell'interfaccia REST Astra Trident.
+
--

WARNING: L'interfaccia REST di Trident può essere configurata per l'ascolto e la distribuzione solo su 127.0.0.1 (per IPv4) o [::1] (per IPv6).

--


====


== Opzioni di comando e flag



=== `create`

Utilizzare `create` Comando per aggiungere una risorsa ad Astra Trident.

Utilizzo::


[listing]
----
tridentctl create [option]
----
Opzioni:: Aggiungi un backend ad Astra Trident.




=== `delete`

Utilizzare `delete` Comando per rimuovere una o più risorse da Astra Trident.

Utilizzo::


[listing]
----
tridentctl delete [option]
----
Opzioni:: Elimina uno o più backend di storage da Astra Trident.
`snapshot`:: Elimina uno o più snapshot di volume da Astra Trident.
`storageclass`:: Elimina una o più classi di storage da Astra Trident.
`volume`:: Elimina uno o più volumi di storage da Astra Trident.




=== `get`

Utilizzare `get` Comando per ottenere una o più risorse da Astra Trident.

Utilizzo::


[listing]
----
tridentctl get [option]
----
Opzioni:: Ottieni uno o più backend di storage da Astra Trident.
`snapshot`:: Ottieni uno o più snapshot da Astra Trident.
`storageclass`:: Ottieni una o più classi di storage da Astra Trident.
`volume`:: Ottieni uno o più volumi da Astra Trident.
Allarmi:: Aiuto per i volumi.
`--parentOfSubordinate string`:: Limitare la query al volume di origine subordinato.
`--subordinateOf string`:: Limitare la query ai subordinati del volume.




=== `images`

Utilizzare `images` Flag per stampare una tabella delle immagini container di cui Astra Trident ha bisogno.

Utilizzo::


[listing]
----
tridentctl images [flags]
----
Allarmi:: Guida per le immagini.
`-v`, `--k8s-version string`:: Versione semantica del cluster Kubernetes.




=== `import volume`

Utilizzare `import volume` Comando per importare un volume esistente in Astra Trident.

Utilizzo::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
Alias:: `volume, v`
Allarmi:: Percorso del file PVC YAML o JSON.
`-h`, `--help`:: Guida per il volume.
`--no-manage`:: Creare solo PV/PVC. Non presupporre la gestione del ciclo di vita dei volumi.




=== `install`

Utilizzare `install` Flag per installare Astra Trident.

Utilizzo::


[listing]
----
tridentctl install [flags]
----
Allarmi:: L'immagine contenitore per la telemetria AutoSupport (predefinita "netapp/trident autosupport:<current-version>").
`--autosupport-proxy string`:: L'indirizzo/porta di un proxy per l'invio della telemetria AutoSupport.
`--enable-node-prep`:: Tentare di installare i pacchetti richiesti sui nodi.
`--generate-custom-yaml`:: Generare file YAML senza installare nulla.
`-h`, `--help`:: Guida per l'installazione.
`--http-request-timeout`:: Ignorare il timeout della richiesta HTTP per l'API REST del controller Trident (valore predefinito 1m30).
`--image-registry string`:: L'indirizzo/porta di un registro di immagine interno.
`--k8s-timeout duration`:: Il timeout per tutte le operazioni Kubernetes (predefinito 3 m0).
`--kubelet-dir string`:: La posizione host dello stato interno di kubelet (default "/var/lib/kubelet").
`--log-format string`:: Il formato di registrazione Astra Trident (text, json) (default "text").
`--pv string`:: Il nome del PV legacy utilizzato da Astra Trident, garantisce che non esista (il "tridente" predefinito).
`--pvc string`:: Il nome del PVC legacy utilizzato da Astra Trident, garantisce che non esista (default "tridente").
`--silence-autosupport`:: Non inviare automaticamente pacchetti AutoSupport a NetApp (default true).
`--silent`:: Disattivare la maggior parte dell'output durante l'installazione.
`--trident-image string`:: Immagine Astra Trident da installare.
`--use-custom-yaml`:: Utilizzare i file YAML esistenti nella directory di installazione.
`--use-ipv6`:: Utilizza IPv6 per le comunicazioni di Astra Trident.




=== `logs`

Utilizzare `logs` Flag per stampare i log da Astra Trident.

Utilizzo::


[listing]
----
tridentctl logs [flags]
----
Allarmi:: Creare un archivio di supporto con tutti i registri, se non diversamente specificato.
`-h`, `--help`:: Guida per i registri.
`-l`, `--log string`:: Log di Astra Trident da visualizzare. Uno tra trident|auto|trident-operator|all (impostazione predefinita "auto").
`--node string`:: Il nome del nodo Kubernetes da cui raccogliere i log dei pod dei nodi.
`-p`, `--previous`:: Ottenere i log per l'istanza contenitore precedente, se esiste.
`--sidecars`:: Ottenere i log per i contenitori sidecar.




=== `send`

Utilizzare `send` Comando per inviare una risorsa da Astra Trident.

Utilizzo::


[listing]
----
tridentctl send [option]
----
Opzioni:: Inviare un archivio AutoSupport a NetApp.




=== `uninstall`

Utilizzare `uninstall` Flag per disinstallare Astra Trident.

Utilizzo::


[listing]
----
tridentctl uninstall [flags]
----
Allarmi:: Guida per la disinstallazione.
`--silent`:: Disattivare la maggior parte dell'output durante la disinstallazione.




=== `update`

Utilizzare `update` Comando per modificare una risorsa in Astra Trident.

Utilizzo::


[listing]
----
tridentctl update [option]
----
Opzioni:: Aggiorna un backend in Astra Trident.




=== `update backend state`

Utilizzare `update backend state` comando per sospendere o riprendere le operazioni di backend.

Utilizzo::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
Allarmi:: Impostare su `suspended` per sospendere le operazioni di backend. Impostare su `normal` per riprendere le operazioni di backend. Quando è impostato su `suspended`:
+
--
* `AddVolume`, `CloneVolume`, `Import Volume`, `ResizeVolume` sono in pausa.
* `PublishVolume`, `UnPublishVolume`, `CreateSnapshot`, `GetSnapshot`, `RestoreSnapshot`, `DeleteSnapshot`, `RemoveVolume`, `GetVolumeExternal`, `ReconcileNodeAccess` rimangono disponibili.


--
`-h`, `--help`:: Guida per lo stato backend.




=== `version`

Utilizzare `version` contrassegni per stampare la versione di `tridentctl` E il servizio Running Trident.

Utilizzo::


[listing]
----
tridentctl version [flags]
----
Allarmi:: Solo versione client (nessun server richiesto).
`-h, --help`:: Guida per la versione.

